services:
  dockergameserver:
    image: ${DOCKER_REGISTRY-}dockergameserver
    build:
      context: .
      dockerfile: src/DockerGameServer/Dockerfile
    user: root
    environment:
      - ASPNETCORE_ENVIRONMENT=production
      - ASPNETCORE_URLS=http://+:8080
      - Servers__Path=/app/servers
      - Security__MasterKey=${SECURITY_MASTERKEY}
      - Security__HashPepper=${SECURITY_HASHPEPPER}
      - ConnectionStrings__PostgresDb=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      # Docker socket for Docker.DotNet
      - /var/run/docker.sock:/var/run/docker.sock

      # Host folder for server data (persistent, shared with Server containers)
      - /opt/gameservers:/app/servers
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
